### PR TITLE
Updated the roadmap from the 2023 workshop

### PR DESCRIPTION
**Pull request by freemansw1**
This updates the roadmap from our 2023 post-workshop discussions, with some minor edits.

### CODE REVIEW

**Review by fsenf — APPROVED** [review]
@freemansw1 : I really thank you a lot for this update. I have some micro edits which I will provide as small PR to your branch. Beside, I am happy this dirty corner in our tobac-project has now been cleaned up ;-)

**Review by JuliaKukulies — COMMENTED** [review]
Thank you for getting this over here @freemansw1! I agree with the minor changes of @fsenf to the references.  And, do we want to add information about the steering committee members as in our google drive version of not? 

Another minor thought: "Increase the sustainability of development" and "Implement a sustainable framework within tobac, including well-defined data models" in the 3 year goals sounds almost the same? If you agree, I would remove the first of the two since the second is a bit more specific.

**Comment by fsenf** [comment]
@freemansw1 : There is an roadmap update waiting on your fork if you would accept it then we could proceed towards an roadmap update.
@JuliaKukulies : I would tend to keep both statements: one is with regard to the sustainability of the development process (e.g. funding for development) and the other w.r.t. the software framework.

**Comment by freemansw1** [comment]
> @freemansw1 : There is an roadmap update waiting on your fork if you would accept it then we could proceed towards an roadmap update. @JuliaKukulies : I would tend to keep both statements: one is with regard to the sustainability of the development process (e.g. funding for development) and the other w.r.t. the software framework.

Thanks, Fabian. Do we want me to merge this version as-is or do we want to wait for your edits?

**Pull request merged**
